### ISSUE TITLE
Start node error

### ISSUE THREAD

**Issue by blocknodehub** [bit-country/Metaverse-Network#312]
Ubuntu 22.04
I try to since the compiler (https://github.com/bit-country/Metaverse-Network/blob/master/NODE.md), and use bitcountry/ continuon-collator-node :fdf74a4, this problem occurs

ws://xxx.xxx.com:xxxx is a full node

 ./metaverse-node  --base-path=/xxx/xxx/node --database=rocksdb  --execution=wasm  --wasm-execution=compiled --relay-chain-rpc-urls ws://xxx.xxx.com:xxxx --state-cache-size=0 --db-cache=4000 --unsafe-rpc-external --rpc-methods=unsafe --rpc-cors=all --rpc-port=9933 --port=30333 --state-pruning=archive --blocks-pruning=archive

I followed the above command to start the node, but an error was reported:

thread 'main' panicked at 'Mismatch between definition and access of `relay_chain_rpc_urls`. Could not downcast to TypeId { t: 12832920143938018242 }, need to downcast to TypeId { t: 3357029650088529668 }
', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.3.11/src/parser/error.rs:32:9
stack backtrace:
   0:     0x558535a0cc91 - std::backtrace_rs::backtrace::libunwind::trace::h1fcde0ea8f9a8cac
                               at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x558535a0cc91 - std::backtrace_rs::backtrace::trace_unsynchronized::h3bfe5daa881a502d
                               at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x558535a0cc91 - std::sys_common::backtrace::_print_fmt::h6c9a5949f87a0a7a
                               at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x558535a0cc91 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h60e57e557d9992ea
                               at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x558535a3603f - core::fmt::rt::Argument::fmt::h32fe9cf7fd31466e
                               at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/core/src/fmt/rt.rs:138:9
   5:     0x558535a3603f - core::fmt::write::h456644d486ec276c
                               at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/core/src/fmt/mod.rs:1094:21
   6:     0x558535a08d41 - std::io::Write::write_fmt::h2c3a3e95369085f2
                               at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/io/mod.rs:1712:15
   7:     0x558535a0caa5 - std::sys_common::backtrace::_print::h4a02a819355b63b1
                               at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x558535a0caa5 - std::sys_common::backtrace::print::h07577b83e8248693
                               at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x558535a0e117 - std::panicking::default_hook::{{closure}}::hcb1bab104892ac31
  10:     0x558535a0df04 - std::panicking::default_hook::h0cc6f3347f4b8e64
                               at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/panicking.rs:288:9
  11:     0x558535a0e5b1 - std::panicking::rust_panic_with_hook::hfc3e471ec066cbc7
                               at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/panicking.rs:691:13
  12:     0x558535a0e4a7 - std::panicking::begin_panic_handler::{{closure}}::h3c341139318c1a03
                               at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/panicking.rs:582:13
  13:     0x558535a0d0c6 - std::sys_common::backtrace::__rust_end_short_backtrace::hf4ec24f3648d6c4f
                               at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/sys_common/backtrace.rs:151:18
  14:     0x558535a0e212 - rust_begin_unwind
                               at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/panicking.rs:578:5
  15:     0x55853319f083 - core::panicking::panic_fmt::he143d7274df42268
                               at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/core/src/panicking.rs:67:14
  16:     0x5585332a1511 - clap_builder::parser::error::MatchesError::unwrap::h8ee95028e9a0dba3
  17:     0x558533c2557e - sc_cli::SubstrateCli::from_args::h438d9fddbc92f861
  18:     0x558533b92600 - metaverse_node::command::run::h5b8b93e3858fc8dd
  19:     0x5585332850e9 - metaverse_node::main::hec1421010e38a62b
  20:     0x5585338d7597 - std::sys_common::backtrace::__rust_begin_short_backtrace::h10800b85314be002
  21:     0x5585338d75d5 - std::rt::lang_start::{{closure}}::h1f1b8fc7260a377a
  22:     0x5585359ff595 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h79627e11ffa7b30b
                               at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/core/src/ops/function.rs:284:13
  23:     0x5585359ff595 - std::panicking::try::do_call::h3bc2032636a54fd4
                               at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/panicking.rs:485:40
  24:     0x5585359ff595 - std::panicking::try::ha6c61ffcd389d3b2
                               at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/panicking.rs:449:19
  25:     0x5585359ff595 - std::panic::catch_unwind::h3b314122186203b8
                               at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/panic.rs:142:14
  26:     0x5585359ff595 - std::rt::lang_start_internal::{{closure}}::hf510b5c01edf08c2
                               at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/rt.rs:148:48
  27:     0x5585359ff595 - std::panicking::try::do_call::h99df6c60189f60aa
                               at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/panicking.rs:485:40
  28:     0x5585359ff595 - std::panicking::try::ha687945c084f2706
                               at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/panicking.rs:449:19
  29:     0x5585359ff595 - std::panic::catch_unwind::h6d69a2287085530b
                               at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/panic.rs:142:14
  30:     0x5585359ff595 - std::rt::lang_start_internal::h017a38677faa6368
                               at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/rt.rs:148:20
  31:     0x558533285115 - main
  32:     0x7f89abd4ad90 - <unknown>
  33:     0x7f89abd4ae40 - __libc_start_main
  34:     0x5585331cd005 - _start
  35:                0x0 - <unknown>

**Comment by tantran2019** [comment]
> Ubuntu 22.04 chain: poineer I try to since the compiler (https://github.com/bit-country/Metaverse-Network/blob/master/NODE.md), and use Docker image: bitcountry/pioneer-collattor-node:31e473a, this problem occurs
> 
> ws://xxx.xxx.com:xxxx is a full node
> 
> ./metaverse-node --base-path=/xxx/xxx/node --database=rocksdb --execution=wasm --wasm-execution=compiled --relay-chain-rpc-urls ws://xxx.xxx.com:xxxx --state-cache-size=0 --db-cache=4000 --unsafe-rpc-external --rpc-methods=unsafe --rpc-cors=all --rpc-port=9933 --port=30333 --state-pruning=archive --blocks-pruning=archive
> 
> I followed the above command to start the node, but an error was reported:
> 
> thread 'main' panicked at 'Mismatch between definition and access of `relay_chain_rpc_urls`. Could not downcast to TypeId { t: 12832920143938018242 }, need to downcast to TypeId { t: 3357029650088529668 } ', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.3.11/src/parser/error.rs:32:9 stack backtrace: 0: 0x558535a0cc91 - std::backtrace_rs::backtrace::libunwind::trace::h1fcde0ea8f9a8cac at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5 1: 0x558535a0cc91 - std::backtrace_rs::backtrace::trace_unsynchronized::h3bfe5daa881a502d at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5 2: 0x558535a0cc91 - std::sys_common::backtrace::_print_fmt::h6c9a5949f87a0a7a at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/sys_common/backtrace.rs:65:5 3: 0x558535a0cc91 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h60e57e557d9992ea at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/sys_common/backtrace.rs:44:22 4: 0x558535a3603f - core::fmt::rt::Argument::fmt::h32fe9cf7fd31466e at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/core/src/fmt/rt.rs:138:9 5: 0x558535a3603f - core::fmt::write::h456644d486ec276c at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/core/src/fmt/mod.rs:1094:21 6: 0x558535a08d41 - std::io::Write::write_fmt::h2c3a3e95369085f2 at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/io/mod.rs:1712:15 7: 0x558535a0caa5 - std::sys_common::backtrace::_print::h4a02a819355b63b1 at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/sys_common/backtrace.rs:47:5 8: 0x558535a0caa5 - std::sys_common::backtrace::print::h07577b83e8248693 at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/sys_common/backtrace.rs:34:9 9: 0x558535a0e117 - std::panicking::default_hook::{{closure}}::hcb1bab104892ac31 10: 0x558535a0df04 - std::panicking::default_hook::h0cc6f3347f4b8e64 at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/panicking.rs:288:9 11: 0x558535a0e5b1 - std::panicking::rust_panic_with_hook::hfc3e471ec066cbc7 at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/panicking.rs:691:13 12: 0x558535a0e4a7 - std::panicking::begin_panic_handler::{{closure}}::h3c341139318c1a03 at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/panicking.rs:582:13 13: 0x558535a0d0c6 - std::sys_common::backtrace::__rust_end_short_backtrace::hf4ec24f3648d6c4f at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/sys_common/backtrace.rs:151:18 14: 0x558535a0e212 - rust_begin_unwind at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/panicking.rs:578:5 15: 0x55853319f083 - core::panicking::panic_fmt::he143d7274df42268 at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/core/src/panicking.rs:67:14 16: 0x5585332a1511 - clap_builder::parser::error::MatchesError::unwrap::h8ee95028e9a0dba3 17: 0x558533c2557e - sc_cli::SubstrateCli::from_args::h438d9fddbc92f861 18: 0x558533b92600 - metaverse_node::command::run::h5b8b93e3858fc8dd 19: 0x5585332850e9 - metaverse_node::main::hec1421010e38a62b 20: 0x5585338d7597 - std::sys_common::backtrace::__rust_begin_short_backtrace::h10800b85314be002 21: 0x5585338d75d5 - std::rt::lang_start::{{closure}}::h1f1b8fc7260a377a 22: 0x5585359ff595 - core::ops::function::impls::<impl core::ops::function::FnOnce for &F>::call_once::h79627e11ffa7b30b at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/core/src/ops/function.rs:284:13 23: 0x5585359ff595 - std::panicking::try::do_call::h3bc2032636a54fd4 at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/panicking.rs:485:40 24: 0x5585359ff595 - std::panicking::try::ha6c61ffcd389d3b2 at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/panicking.rs:449:19 25: 0x5585359ff595 - std::panic::catch_unwind::h3b314122186203b8 at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/panic.rs:142:14 26: 0x5585359ff595 - std::rt::lang_start_internal::{{closure}}::hf510b5c01edf08c2 at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/rt.rs:148:48 27: 0x5585359ff595 - std::panicking::try::do_call::h99df6c60189f60aa at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/panicking.rs:485:40 28: 0x5585359ff595 - std::panicking::try::ha687945c084f2706 at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/panicking.rs:449:19 29: 0x5585359ff595 - std::panic::catch_unwind::h6d69a2287085530b at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/panic.rs:142:14 30: 0x5585359ff595 - std::rt::lang_start_internal::h017a38677faa6368 at /rustc/9d871b0617a4b3d6610b7cee0ab5310dcb542c62/library/std/src/rt.rs:148:20 31: 0x558533285115 - main 32: 0x7f89abd4ad90 - 33: 0x7f89abd4ae40 - __libc_start_main 34: 0x5585331cd005 - _start 35: 0x0 -

It appears you might have used the wrong Kusama snapshot. 
Here is the Kusama snapshot link you can refer to: [](https://ksm-rocksdb.polkashots.io/)
I'd recommend creating an issue on the Polkadot repository to get the appropriate assistance.
